[project]
name = "mastodon-archiver"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.9"
dependencies = [
    "cappa>=0.22.4",
    "jinja2>=3.1.4",
    "pydantic>=2.9.0",
    "structlog>=24.4.0",
]
